version: '4.4.4'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 5002:5000
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_DB: reddiget

    volumes:
      - .dbdata:/var/lib/postgres/data\
    ports:
      - 33072:5432